### PR TITLE
Update UserManagementPanel.java so that the password button works

### PR DESCRIPTION
**Pull request by fredepd**
Fixed the change password button

### CODE REVIEW

**Comment by Zenexer** [comment]
@fredepd Your changes don't compile and you made them on the wrong branch (see email).  Your task is incomplete until you fix your code and push to the correct branch.  Please use a proper IDE and ensure that you don't introduce any errors or warnings.  You can find instructions for configuring IntelliJ [on the wiki](https://github.com/massbay-cs/cs225-proj4/wiki/IntelliJ).

Compiler errors: https://travis-ci.org/massbay-cs/cs225-proj4/builds/124096843#L171

cc @AndrewWelch33

**Comment by fredepd** [comment]
Everything compiles and runs fine in NetBeans and I see from the code that I somehow messed it up it while uploading to Github, which I don't really know how to use.  Should I be pushing to the frontend branch?

**Comment by Zenexer** [comment]
Yes, frontend branch is best for this.  I haven't actually tested it myself, but the errors indicate there may be some import statements missing from your original commit.  If you can't figure out what's missing, I can give it a closer look.

**Comment by fredepd** [comment]
OK, it seems like it should be properly pushed onto the frontend branch.

**Pull request closed without merging**
